[tool.ariadne-codegen]
schema_path = "graphql/schema.graphql"
queries_path = "graphql/queries.graphql"
target_package_name = "graphql"
target_package_path = "src/client"
package_name = "client.graphql"
